/*
	@Polski TOP Serwer - Command.inc
	@Last update: 19 marca 2014 21:52

*/
#include "ptsDM/server_commands/gangs.inc"
#include "ptsDM/server_commands/cars.inc"
#include "ptsDM/server_commands/games.inc"
#include "ptsDM/server_commands/teles.inc"
#include "ptsDM/server_commands/off.inc"
#include "ptsDM/server_commands/anims.inc"
#include "ptsDM/server_commands/admin.inc"
#include "ptsDM/server_commands/user.inc"
#include "ptsDM/server_commands/vip.inc"